### ISSUE TITLE
Make "vidi" required

### ISSUE THREAD

**Issue by fsuter** [Ecodev/formule#85]
Currently "vidi" is suggested in the ext_emconf.php file. While there are conditions checking for "vidi" installation in ext_tables.php, "vidi" classes are explicitly required in Configuration/TCA/tx_formule_domain_model_sentmessage.php. This means that "vidi" is not optional...

**Comment by fabarea** [comment]
True, it should be added some condition in this `sentmessage.php` whether Vidi is loaded or not. Vidi is not required by Formule in any form but suggested as it can displayed a "sent messages" (log of sent module) module in the BE.

**Comment by fsuter** [comment]
Indeed, it would be even better if one did not have to install vidi at all!

**Comment by AndreasA** [comment]
Will this be fixed in 1.0.2?
Not really related but what about 8.x support (or does it already work and only the entry in ext_emconf.php is wrong)?

**Comment by fabarea** [comment]
Released as well. 

@AndreasA I haven't tested with 8.x yet. Let me know in case you have the chance to test against that version.

**Comment by AndreasA** [comment]
Not currently but maybe in the near future, I will let you know once I have done so.
But as long as it will work with 8.x LTS it should be enough :)
