### ISSUE TITLE
Security: client can get around field validation by using GET request

### ISSUE THREAD

**Issue by stissot** [Ecodev/formule#87]
A malicious user can use a tx_formule form to send spam with a request like this: `GET /home/?tx_formule_pi1%5Baction%5D=submit&tx_formule_pi1%5Bcontroller%5D=Form&cHash=c2d0bd90d58a8f83a91ae4c4c48a72a4`. An error message is returned, but the email to the admin/user gets sent nevertheless. The request can be reused again and again, without changing the cHash.
When submitting the form using GET instead of POST, it seems there is no field validation, even if the anti-spam feature and honeypot are enabled.

**Comment by stissot** [comment]
The problem was that `submitAction` in `FormController` was accepting GET requests, I've added a check that throws an Exception if the request type is not POST.

**Comment by PowerKiKi** [comment]
Same case on different site. Thanks for the fix, I'll update all our sites.
